## NUMERICAL PYTHON 

In [1]:
import numpy as np
a1=[1,2,3,4]
a=np.array([1,2,3,4])
print('list =',a1)
print(a.shape)
print(a)

list = [1, 2, 3, 4]
(4,)
[1 2 3 4]


In [34]:
b=np.array([[1,2],[3,4]])
print(b.shape)
print(b)  
print(b.ndim)
print(b.dtype)        

(2, 2)
[[1 2]
 [3 4]]
2
int64


In [35]:
#CHECKING DATATYPE OF ARRAY
b=np.array([[1,2],[3,4]])
print(b)
print(b.dtype)

[[1 2]
 [3 4]]
int64


In [36]:
#checking number of axes
b=np.array([[1,2],[3,4]])
print(b)
print('Dimensions =',b.ndim)

[[1 2]
 [3 4]]
Dimensions = 2


In [37]:
#checking dimensions of the array
b=np.array([[1,2],[3,4]])
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [38]:
# checking size of the array
b=np.array([[1,2],[3,4]])
print(b)
print(b.size)

[[1 2]
 [3 4]]
4


In [66]:
#change datatype 
b=np.array([[1,2],[3,4]])
print(b)
print(b.dtype)                                                        #int8 max value = 127
b=np.array([[100,200],[400,256]],dtype = np.int8)
print(b)
print(b.dtype)


[[1 2]
 [3 4]]
int64
[[ 100  -56]
 [-112    0]]
int8


In [40]:
#CREATING 2 DIMENSIONAL ARRAY
a=np.array([[1,2],[3,4]])
print('Dimensions =',a.ndim)

Dimensions = 2


In [41]:
#CREATING 2 DIMENSIONAL ARRAY
a=np.array([[[1,2],[3,4]]])
print('Dimensions =',a.ndim)

Dimensions = 3


In [11]:
# ARANGING 
print(np.arange(5,1001,2))

[  5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37  39
  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73  75
  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109 111
 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143 145 147
 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179 181 183
 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215 217 219
 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251 253 255
 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287 289 291
 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323 325 327
 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359 361 363
 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395 397 399
 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431 433 435
 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467 469 471
 473 475 477 479 481 483 485 487 489 491 493 495 49

In [14]:
# USE OF LINSPACE
a=np.linspace(r x in range(0,13):
    b=b+[x**2]
b=np.array(b)
print(b)1,15,5)
print(a)

[ 1.   4.5  8.  11.5 15. ]


In [9]:
import numpy as np
a=np.random.randint(1,100,25)
b=np.array(a)
print(b)
print(a)

[ 2 50  1  5 33 75 89 99 67  8 30  7 33 49 67 47 59 62 69 71 29 82 15 19
  5]
[ 2 50  1  5 33 75 89 99 67  8 30  7 33 49 67 47 59 62 69 71 29 82 15 19
  5]
