# ☺••DATAFRAMES••☺

## ♫ Creating Dataframes ♫

In [1]:
#empty dataframe
import pandas as pd          #pandas.DataFrame( data, index, column)#
a=pd.DataFrame()
print(a)

Empty DataFrame
Columns: []
Index: []


### ♪ Creating a DataFrame from List of Dictionaries ♪

In [17]:
import pandas as pd
a=pd.DataFrame([{101:"Annany",102:"Aryan",103:"Bhavesh"},{102:"Ishita",103:"Kritika"}])
print(a)

      101     102      103
0  Annany   Aryan  Bhavesh
1     NaN  Ishita  Kritika


### ♪ Creating a DataFrame from List of Lists ♪

In [37]:
import pandas as pd
a=pd.DataFrame([["Annany","Aryan","Bhavesh"],[None,"Ishita","Kritika"]])
print(a)
a=pd.DataFrame([["Annany","Aryan","Bhavesh"],[None,"Ishita","Kritika"]],[4,9],[4,9,16])
print(a)
a=pd.DataFrame([["~~~","","~~~"],["","w",""]],['',''],['','',''])
print(a)

        0       1        2
0  Annany   Aryan  Bhavesh
1    None  Ishita  Kritika
       4       9        16
4  Annany   Aryan  Bhavesh
9    None  Ishita  Kritika
             
  ~~~     ~~~
       w     


### ♪ Creating a DataFrame from Dictionary of Lists ♪

In [39]:
import pandas as pd
a=pd.DataFrame({"A":[120,110,100,90],"B":[50,60,70,80],"C":[40,30,20,10]})
print(a)

     A   B   C
0  120  50  40
1  110  60  30
2  100  70  20
3   90  80  10


### ♪ Creating a DataFrame from List of Dictionaries ♪

In [47]:
import pandas as pd
a=pd.DataFrame([{"A":1,"B":2,"C":3},{"A":6,"B":5,"C":4},{"A":7,"B":8,"C":9}])
print(a)
l1=[{101:"Ansh",102:"Moonal",103:"Devansh"}, {102:"Rashi",103:"Pranjal"}]
df=pd.DataFrame(l1)
print(df)

   A  B  C
0  1  2  3
1  6  5  4
2  7  8  9
    101     102      103
0  Ansh  Moonal  Devansh
1   NaN   Rashi  Pranjal


### ♪ Creating a DataFrame from Dictionary of Series 

In [48]:
import pandas as pd
a=[5,4,3]
b=[4,5,2]
c=[3,2,5]
d=pd.DataFrame({"A":pd.Series(a),"B":pd.Series(b),"C":pd.Series(c)})
print(d)

   A  B  C
0  5  4  3
1  4  5  2
2  3  2  5


### ♪ Create Dataframe from Text/CSV Files ♪

In [52]:
import pandas as pd
a=pd.read_csv('matches.csv')
print(a.head())

   id  season       city        date                        team1  \
0   1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06               Mumbai Indians   
2   3    2017     Rajkot  2017-04-07                Gujarat Lions   
3   4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4   5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   
3              Kings XI Punjab              Kings XI Punjab         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad     

### ♪ Customising Labels ♪

In [56]:
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c],[1,2,1],[1,2,1])
print(d)

   1  2  1
1  2  1  2
2  1  2  1
1  2  1  2


## ♫ DATAFRAME ATTRIBUTES ♫

### ♪ size ♪

In [65]:
#Return an int representing the number of elements in given dataframe. #
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.size)

9


### ♪ shape ♪

In [64]:
#Return a tuple representing the dimensions of the DataFrame#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.shape)

(3, 3)


### ♪ axes ♪

In [63]:
#Return a list representing the axes of the DataFrame.#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.axes)

[RangeIndex(start=0, stop=3, step=1), RangeIndex(start=0, stop=3, step=1)]


### ♪ ndim ♪

In [66]:
#Return an int representing the number of axes / array dimensions#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.ndim)

2


### ♪ columns  ♪

In [75]:
#The column labels of the DataFrame#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c]) 
print(d.columns,"DEFAULTTTT")
d=pd.DataFrame([a,b,c],np.arange(3),[4,2,1]) 
print(d.columns,"Labelled")

RangeIndex(start=0, stop=3, step=1) DEFAULTTTT
Int64Index([4, 2, 1], dtype='int64') Labelled


### ♪ values ♪

In [78]:
#Return a Numpy representation of the DataFrame#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.values)

[[2 1 2]
 [1 2 1]
 [2 1 2]]


### ♪ empty ♪

In [80]:
#Indicator whether DataFrame is empty#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.empty)

False


## ♫ Operations on rows and columns in DataFrames ♫

### ♪ Adding a new Column to a DataFrame ♪

In [91]:
import pandas as pd
a=pd.DataFrame({"A":[1,2,3,4],"B":[8,7,6,5],"C":[9,10,11,12]})
a["D"]=[19,15,14,13]
print(a)
a["E"]=[20,21,22,23]
print(a)

   A  B   C   D
0  1  8   9  19
1  2  7  10  15
2  3  6  11  14
3  4  5  12  13
   A  B   C   D   E
0  1  8   9  19  20
1  2  7  10  15  21
2  3  6  11  14  22
3  4  5  12  13  23


### ♪ Adding a New Row to DataFrame ♪

### ♪ Deleting Rows or Columns from a DataFrame ♪