# ☺••DATAFRAMES••☺

## ♫ Creating Dataframes ♫

In [1]:
#empty dataframe
import pandas as pd          #pandas.DataFrame( data, index, column)#
a=pd.DataFrame()
print(a)

Empty DataFrame
Columns: []
Index: []


### ♪ Creating a DataFrame from List of Dictionaries ♪

In [17]:
import pandas as pd
a=pd.DataFrame([{101:"Annany",102:"Aryan",103:"Bhavesh"},{102:"Ishita",103:"Kritika"}])
print(a)

      101     102      103
0  Annany   Aryan  Bhavesh
1     NaN  Ishita  Kritika


### ♪ Creating a DataFrame from List of Lists ♪

In [37]:
import pandas as pd
a=pd.DataFrame([["Annany","Aryan","Bhavesh"],[None,"Ishita","Kritika"]])
print(a)
a=pd.DataFrame([["Annany","Aryan","Bhavesh"],[None,"Ishita","Kritika"]],[4,9],[4,9,16])
print(a)
a=pd.DataFrame([["~~~","","~~~"],["","w",""]],['',''],['','',''])
print(a)

        0       1        2
0  Annany   Aryan  Bhavesh
1    None  Ishita  Kritika
       4       9        16
4  Annany   Aryan  Bhavesh
9    None  Ishita  Kritika
             
  ~~~     ~~~
       w     


### ♪ Creating a DataFrame from Dictionary of Lists ♪

In [39]:
import pandas as pd
a=pd.DataFrame({"A":[120,110,100,90],"B":[50,60,70,80],"C":[40,30,20,10]})
print(a)

     A   B   C
0  120  50  40
1  110  60  30
2  100  70  20
3   90  80  10


### ♪ Creating a DataFrame from List of Dictionaries ♪

In [47]:
import pandas as pd
a=pd.DataFrame([{"A":1,"B":2,"C":3},{"A":6,"B":5,"C":4},{"A":7,"B":8,"C":9}])
print(a)
l1=[{101:"Ansh",102:"Moonal",103:"Devansh"}, {102:"Rashi",103:"Pranjal"}]
df=pd.DataFrame(l1)
print(df)

   A  B  C
0  1  2  3
1  6  5  4
2  7  8  9
    101     102      103
0  Ansh  Moonal  Devansh
1   NaN   Rashi  Pranjal


### ♪ Creating a DataFrame from Dictionary of Series 

In [48]:
import pandas as pd
a=[5,4,3]
b=[4,5,2]
c=[3,2,5]
d=pd.DataFrame({"A":pd.Series(a),"B":pd.Series(b),"C":pd.Series(c)})
print(d)

   A  B  C
0  5  4  3
1  4  5  2
2  3  2  5


### ♪ Create Dataframe from Text/CSV Files ♪

In [52]:
import pandas as pd
a=pd.read_csv('matches.csv')
print(a.head())

   id  season       city        date                        team1  \
0   1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06               Mumbai Indians   
2   3    2017     Rajkot  2017-04-07                Gujarat Lions   
3   4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4   5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   
3              Kings XI Punjab              Kings XI Punjab         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad     

### ♪ Customising Labels ♪

In [56]:
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c],[1,2,1],[1,2,1])
print(d)

   1  2  1
1  2  1  2
2  1  2  1
1  2  1  2


## ♫ DATAFRAME ATTRIBUTES ♫

### ♪ size ♪

In [65]:
#Return an int representing the number of elements in given dataframe. #
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.size)

9


### ♪ shape ♪

In [64]:
#Return a tuple representing the dimensions of the DataFrame#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.shape)

(3, 3)


### ♪ axes ♪

In [63]:
#Return a list representing the axes of the DataFrame.#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.axes)

[RangeIndex(start=0, stop=3, step=1), RangeIndex(start=0, stop=3, step=1)]


### ♪ ndim ♪

In [66]:
#Return an int representing the number of axes / array dimensions#
import pandas as pd
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.ndim)

2


### ♪ columns  ♪

In [75]:
#The column labels of the DataFrame#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c]) 
print(d.columns,"DEFAULTTTT")
d=pd.DataFrame([a,b,c],np.arange(3),[4,2,1]) 
print(d.columns,"Labelled")

RangeIndex(start=0, stop=3, step=1) DEFAULTTTT
Int64Index([4, 2, 1], dtype='int64') Labelled


### ♪ values ♪

In [78]:
#Return a Numpy representation of the DataFrame#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.values)

[[2 1 2]
 [1 2 1]
 [2 1 2]]


### ♪ empty ♪

In [80]:
#Indicator whether DataFrame is empty#
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
print(d.empty)

False


###  ♪ index ♪

In [42]:
import pandas as pd
import numpy as np
a=[2,1,2]
b=[1,2,1]
c=[2,1,2]
d=pd.DataFrame([a,b,c])
d.index=['A',"b","C"]
print(d)

   0  1  2
A  2  1  2
b  1  2  1
C  2  1  2


## ♫ Operations on rows and columns in DataFrames ♫

### ♪ Adding a new Column to a DataFrame ♪

In [8]:
import pandas as pd
a=pd.DataFrame({0:[1,2,3],15:[14,13,12],16:[17,18,19]},["N","U","M"])
b=pd.DataFrame({4:[5,6,7],11:[10,9,8],20:[21,22,23]},["B","E","R"])
a[2]=[15,16,17]
b[18]=[19,20,21]
print(a)
print(b)


   0   15  16  2 
N   1  14  17  15
U   2  13  18  16
M   3  12  19  17
   4   11  20  18
B   5  10  21  19
E   6   9  22  20
R   7   8  23  21


In [9]:
import pandas as pd
data = {'Rollno':[1,2,3,4],'Name':['Arnab','Amit','Shikha','Sonali'],
        'Total':[350,400,490,450],'Percentage':[70,80,98,90]}
df5 = pd.DataFrame(data)
print('Old Data Frame:-\n',df5)
#Adding New column in a DataFrame

df5['Grade']=['C','B','A','A']
print('New Data Frame:-\n',df5)

Old Data Frame:-
    Rollno    Name  Total  Percentage
0       1   Arnab    350          70
1       2    Amit    400          80
2       3  Shikha    490          98
3       4  Sonali    450          90
New Data Frame:-
    Rollno    Name  Total  Percentage Grade
0       1   Arnab    350          70     C
1       2    Amit    400          80     B
2       3  Shikha    490          98     A
3       4  Sonali    450          90     A


In [16]:
import pandas as pd            #Add new column applying Mathematical Operations#
data = {'Item':["Pencil","Eraser","Ball Pen"],'Price':[100,120,150],'Discount(%)':[30,40,50]}
b = pd.DataFrame(data)
print(b,'\n')
b['Amount']=b['Price']-b['Discount(%)']*b['Price']/100
print(b)

       Item  Price  Discount(%)
0    Pencil    100           30
1    Eraser    120           40
2  Ball Pen    150           50 

       Item  Price  Discount(%)  Amount
0    Pencil    100           30    70.0
1    Eraser    120           40    72.0
2  Ball Pen    150           50    75.0


In [24]:
#New Column add at desired position#
import pandas as pd
data= {'Item':["Pencil","Eraser","Ball Pen"],'Price':[100,120,150],'Discount(%)':[30,40,50]}
b = pd.DataFrame(data)
print(b,'\n')
b.insert(1,'columnadded',[40,50,30])
print(b)

       Item  Price  Discount(%)
0    Pencil    100           30
1    Eraser    120           40
2  Ball Pen    150           50 

       Item  columnadded  Price  Discount(%)
0    Pencil           40    100           30
1    Eraser           50    120           40
2  Ball Pen           30    150           50


In [46]:
#To add column using loc() method#
import pandas as pd
data= {'Item':["Pencil","Eraser","Ball Pen"],'Price':[100,120,150],'Discount(%)':[30,40,50]}
b = pd.DataFrame(data)
print(b,'\n')
b.loc[1:2,'Discount']=[1,2]
print(b)             #no n-1 ka panga neither in default nor in #

       Item  Price  Discount(%)
0    Pencil    100           30
1    Eraser    120           40
2  Ball Pen    150           50 

       Item  Price  Discount(%)  Discount
0    Pencil    100           30       NaN
1    Eraser    120           40       1.0
2  Ball Pen    150           50       2.0


### ♪ Adding a New Row to DataFrame ♪

In [49]:
#To add Row using loc method#
data = {'Item':["Pencil","Eraser","Ball Pen"],'Price':[100,120,150],'Discount(%)':[30,40,50]}
b = pd.DataFrame(data)
print(b,'\n')
b.loc[4]=["Compass",300,63]
print(b)

       Item  Price  Discount(%)
0    Pencil    100           30
1    Eraser    120           40
2  Ball Pen    150           50 

       Item  Price  Discount(%)
0    Pencil    100           30
1    Eraser    120           40
2  Ball Pen    150           50
4   Compass    300           63


### ♪ Deleting Rows or Columns from a DataFrame ♪

In [53]:
#deleting Columns in a Dataframe with label#
import pandas as pd 
bill ={'itemName':['Pen','Copy','Eraser','Book','Pencil','Ink','Color'],
 'Quantity':[2,10,5,6,4,1,2],
 'Price':[10,20,4,50,6,10,20]}
B = pd.DataFrame(bill, index = [1,2,3,4,5,6,7])
B['Amount'] = B['Quantity'] * B['Price']
B.loc[:,'Sale Price'] = [9,6,5,4,3,2,1]
print(B)
C=B.drop('Sale Price', axis = 1)   #it stores in new variable not some kind of self updating function#
print(C)                               #axis = 1 signifies column#
C=B.drop(4,axis=0)                     #axis = 0 signifies row#
print(C)

  itemName  Quantity  Price  Amount  Sale Price
1      Pen         2     10      20           9
2     Copy        10     20     200           6
3   Eraser         5      4      20           5
4     Book         6     50     300           4
5   Pencil         4      6      24           3
6      Ink         1     10      10           2
7    Color         2     20      40           1
  itemName  Quantity  Price  Amount
1      Pen         2     10      20
2     Copy        10     20     200
3   Eraser         5      4      20
4     Book         6     50     300
5   Pencil         4      6      24
6      Ink         1     10      10
7    Color         2     20      40
  itemName  Quantity  Price  Amount  Sale Price
1      Pen         2     10      20           9
2     Copy        10     20     200           6
3   Eraser         5      4      20           5
5   Pencil         4      6      24           3
6      Ink         1     10      10           2
7    Color         2     20      40     

In [56]:
#deleting Multiple Columns in a Dataframe with label#
import pandas as pd 
bill ={'itemName':['Pen','Copy','Eraser','Book','Pencil','Ink','Color'],
 'Quantity':[2,10,5,6,4,1,2],
 'Price':[10,20,4,50,6,10,20]}
B = pd.DataFrame(bill, index = [1,2,3,4,5,6,7])
B['Amount'] = B['Quantity'] * B['Price']
B.loc[:,'Sale Price'] = [9,6,5,4,3,2,1]
print(B)
C=B.drop(['Price','Sale Price'], axis = 1)#it stores in new variable not some kind o f self updating function#
print(C)                                   #axis = 1 signifies column#
C=B.drop([1,3,6],axis=0)                    #axis = 0 signifies row#
print(C)

  itemName  Quantity  Price  Amount  Sale Price
1      Pen         2     10      20           9
2     Copy        10     20     200           6
3   Eraser         5      4      20           5
4     Book         6     50     300           4
5   Pencil         4      6      24           3
6      Ink         1     10      10           2
7    Color         2     20      40           1
  itemName  Quantity  Amount
1      Pen         2      20
2     Copy        10     200
3   Eraser         5      20
4     Book         6     300
5   Pencil         4      24
6      Ink         1      10
7    Color         2      40
  itemName  Quantity  Price  Amount  Sale Price
2     Copy        10     20     200           6
4     Book         6     50     300           4
5   Pencil         4      6      24           3
7    Color         2     20      40           1


## ♫ Updating Dataframe ♫

In [64]:
import pandas as pd
a={"Rollno":pd.Series([1,2,3,4]),"Total":pd.Series([350.5,400,420]),"Percentage":pd.Series([70,80,84,80])}
b=pd.DataFrame(a)
a.at[1,'Total']=500
print(a)

AttributeError: 'dict' object has no attribute 'at'