## NUMPY PRACTICAL ASSIGNMENT

### Q1. Create an array of 10 elements with values 10 to 1


In [58]:
import numpy as np
a=np.arange(10,1)
print(a)

[]


### Q2. create an array of 3x3 filled with value 10

In [12]:
import numpy as np
a=np.full([3,3],10)
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Q3. Create an array of 20 elements with random numbers between 50 and 100

In [21]:
import numpy as np
a=np.random.randint(50,100,20)
print(a)

[67 53 63 94 67 62 97 82 72 84 94 75 74 66 73 51 55 90 50 80]


### Q4. Create an array of 10 elements with values b/w 1 and 25 with uniform interval.

In [28]:
import numpy as np
a=np.linspace(1,25,10)
print(a)

[ 1.          3.66666667  6.33333333  9.         11.66666667 14.33333333
 17.         19.66666667 22.33333333 25.        ]


### Q5. Create a code to store squares of all elements in array.

In [53]:
import numpy as np
b=[]
for x in range(0,13):
    b=b+[x**2]
b=np.array(b)
print(b)

[  0   1   4   9  16  25  36  49  64  81 100 121 144]


### Q6. WRITE A CODE TO GENERATE RAND NO B/W 1 $ 100 Create array of 5x5.
 

In [8]:
import numpy as np

b=np.random.randint(1,100,(5,5))
print(b,b.shape)

[[52 32 26 86  8]
 [47 49 39 48 38]
 [22 62 86 63 53]
 [57 80 29 36 44]
 [18 29 47 59 12]] (5, 5)
